### ISSUE TITLE
Hi man is not work any more how to fix this problem, can u help me pls😭

### ISSUE THREAD

**Issue by kevinyasuo** [floxay/python-riot-auth#24]
D:\project2\python-riot-auth-main\python-riot-auth-main\examples>python example_auth_argv.py "username" "password"
Traceback (most recent call last):
  File "D:\project2\python-riot-auth-main\python-riot-auth-main\examples\example_auth_argv.py", line 19, in <module>
    asyncio.run(auth.authorize(*CREDS))
  File "D:\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "D:\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\Python311\Lib\site-packages\riot_auth\auth.py", line 217, in authorize
    async with session.put(
  File "D:\Python311\Lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "D:\Python311\Lib\site-packages\aiohttp\client.py", line 643, in _request
    resp.raise_for_status()
  File "D:\Python311\Lib\site-packages\aiohttp\client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://auth.riotgames.com/api/v1/authorization')

**Comment by floxay** [comment]
https://github.com/floxay/python-riot-auth/issues/18#issuecomment-1696033581
https://github.com/floxay/python-riot-auth/issues/18#issuecomment-1696093985

Nothing I can do about it, works fine for me.
