### ISSUE TITLE
Still the 403 error exists

### ISSUE THREAD

**Issue by typhonshambo** [floxay/python-riot-auth#3]
I am getting the 403 error while hosting..

```
%Ignoring exception in command login:
#Traceback (most recent call last):
`  File "/usr/local/lib/python3.10/site-packages/discord/commands/core.py", line 126, in wrapped
    ret = await coro(arg)
`  File "/usr/local/lib/python3.10/site-packages/discord/commands/core.py", line 852, in _invoke
1    await self.callback(self.cog, ctx, **kwargs)
U  File "/home/user_556182600524234793/commands/commands/login.py", line 32, in login
:    userData = await username_to_data(username, password)
i  File "/home/user_556182600524234793/commands/commands/utils/shopData.py", line 19, in username_to_data
!    await auth.authorize(*CREDS)
[  File "/usr/local/lib/python3.10/site-packages/riot_auth/auth.py", line 192, in authorize
    async with session.post(
]  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
"    self._resp = await self._coro
Z  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 640, in _request
    resp.raise_for_status()
j  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
�aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://auth.riotgames.com/api/v1/authorization')

EThe above exception was the direct cause of the following exception:

#Traceback (most recent call last):
i  File "/usr/local/lib/python3.10/site-packages/discord/bot.py", line 993, in invoke_application_command
"    await ctx.command.invoke(ctx)
_  File "/usr/local/lib/python3.10/site-packages/discord/commands/core.py", line 357, in invoke
    await injected(ctx)
`  File "/usr/local/lib/python3.10/site-packages/discord/commands/core.py", line 134, in wrapped
6    raise ApplicationCommandInvokeError(exc) from exc
�discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: ClientResponseError: 403, message='Forbidden', url=URL('https://auth.riotgames.com/api/v1/authorization')
```

**Comment by floxay** [comment]
It's possible that the hosting service you use is banned by Riot in some way.
