### ISSUE TITLE
498 Error

### ISSUE THREAD

**Issue by dupuishugo80** [floxay/python-riot-auth#30]
Hi,

When i try to login i got http 498 Error,

Traceback (most recent call last):
  File "D:\DEV\ValTrack\python-riot-auth\script.py", line 7, in <module>
    asyncio.run(auth.authorize(username="myuser", password="mypassword"))
  File "D:\Python\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\DEV\ValTrack\python-riot-auth\riot_auth\auth.py", line 290, in authorize
    return await self.__fetch_access_token(session, body, headers, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DEV\ValTrack\python-riot-auth\riot_auth\auth.py", line 183, in __fetch_access_token
    async with session.put(
  File "D:\Python\Lib\site-packages\aiohttp\client.py", line 1197, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\aiohttp\client.py", line 696, in _request
    resp.raise_for_status()
  File "D:\Python\Lib\site-packages\aiohttp\client_reqrep.py", line 1070, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 498, message='', url=URL('https://auth.riotgames.com/api/v1/authorization')

Thanks

**Comment by floxay** [comment]
Please consult the below map;
![image](https://github.com/user-attachments/assets/241616c8-d8b9-47d1-bde9-43ad65d53119)

**Comment by dupuishugo80** [comment]
What change should be made to the code with these region codes?

**Comment by floxay** [comment]
Try from a different IP from another country
